version: '3'

vars:
  BUILD_DIR: build
  DOCKER_REPO: tasruntime/github-pr-instances-resource

tasks:
  default:
    cmds:
      - task: test

  generate:
    desc: Generate test fakes
    cmds:
    - go generate ./...
    sources:
    - github.go
    - git.go
    generates:
    - fakes/*.go
    method: checksum

  test:
    desc: Run test suite
    deps: [generate]
    cmds:
    - gofmt -s -l -w .
    - go vet -v ./...
    - go test -race -v ./...

  e2e:
    desc: Run E2E test suite
    cmds:
    - task: test
    - go test -race -v ./... -tags=e2e

  docker:
    desc: Build docker image under dev tag.
    cmds:
    - docker build -t {{.DOCKER_REPO}}:dev .

  build:
    desc: Build check/in/out artifacts
    cmds:
    # - task: test
    - task: go-build
      vars: {BINARY: check}
    - task: go-build
      vars: {BINARY: in}
    - task: go-build
      vars: {BINARY: out}

  go-build:
    cmds:
    - go build -o {{.BUILD_DIR}}/{{.BINARY}}{{exeExt}} -ldflags="-s -w" -v cmd/{{.BINARY}}/main.go
    env:
      CGO_ENABLED: '0'
      GOOS: '{{OS}}'
      GOARCH: '{{ARCH}}'

  ci:
    desc: CI build and tests
    cmds:
    - task: build
    - if [ -n "$(git status --porcelain)" ];then echo "Diff in generated files and/or formatting" && exit 1; fi
    silent: true
